source /home/harshit/teamOS/kernel1/kernel/main/gdt.gdb
source /home/harshit/teamOS/kernel1/kernel/mm/pagetable.gdb
source /home/harshit/teamOS/kernel1/kernel/mm/page.py
source /home/harshit/teamOS/kernel1/kernel/mm/memcheck.py
source /home/harshit/teamOS/kernel1/kernel/mm/slab.py
source /home/harshit/teamOS/kernel1/kernel/proc/kthread.gdb
source /home/harshit/teamOS/kernel1/kernel/proc/proc.py
source /home/harshit/teamOS/kernel1/kernel/util/debug.py
source /home/harshit/teamOS/kernel1/kernel/util/list.py
source /home/harshit/teamOS/kernel1/kernel/vm/vmmap.gdb
