source /home/harshit/Github/Wenix-OS/kernel/main/gdt.gdb
source /home/harshit/Github/Wenix-OS/kernel/mm/pagetable.gdb
source /home/harshit/Github/Wenix-OS/kernel/mm/page.py
source /home/harshit/Github/Wenix-OS/kernel/mm/memcheck.py
source /home/harshit/Github/Wenix-OS/kernel/mm/slab.py
source /home/harshit/Github/Wenix-OS/kernel/proc/kthread.gdb
source /home/harshit/Github/Wenix-OS/kernel/proc/proc.py
source /home/harshit/Github/Wenix-OS/kernel/util/debug.py
source /home/harshit/Github/Wenix-OS/kernel/util/list.py
source /home/harshit/Github/Wenix-OS/kernel/vm/vmmap.gdb
